# Generated by Django 4.2.5 on 2023-10-10 15:09

from django.db import migrations
import test_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0003_alter_department_options_alter_leader_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=test_django.models.IntegerRangeField(default=1, help_text='Введите текущий статус задания: 0 или 1', verbose_name='Статус задания (1 - задание выполнено, 0 - задание не выполнено)'),
        ),
    ]
