# Generated by Django 4.2.5 on 2023-10-10 15:27

from django.db import migrations
import test_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0004_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number',
            field=test_django.models.IntegerRangeField(default=1, help_text='Введите номер задания', verbose_name='Номер задания'),
        ),
    ]
