# Generated by Django 4.2.5 on 2023-11-12 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0006_department_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='leader',
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(default=1, help_text='Выберите отдел', on_delete=django.db.models.deletion.CASCADE, to='test_django.department', verbose_name='Отдел'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leader',
            name='department',
            field=models.ForeignKey(default=1, help_text='Выберите отдел', on_delete=django.db.models.deletion.CASCADE, to='test_django.department', verbose_name='Название отдела'),
        ),
    ]
