# Generated by Django 4.2.5 on 2023-11-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0008_alter_leader_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='department',
            field=models.ForeignKey(help_text='Выберите отдел', on_delete=django.db.models.deletion.CASCADE, to='test_django.department', verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.ForeignKey(default='Отдел backend-разработки', help_text='Выберите отдел', on_delete=django.db.models.deletion.CASCADE, to='test_django.department', verbose_name='Отдел'),
        ),
    ]
