# Generated by Django 4.2.5 on 2023-11-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0010_alter_task_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
    ]
