# Generated by Django 4.2.5 on 2023-11-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0012_task_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='department',
        ),
        migrations.AddField(
            model_name='leader',
            name='team',
            field=models.ForeignKey(default=327, help_text='Выберите группу', on_delete=django.db.models.deletion.CASCADE, to='test_django.team', verbose_name='Номер группы'),
            preserve_default=False,
        ),
    ]
