# Generated by Django 4.2.5 on 2023-12-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0025_remove_leader_department_department_leader_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='teams',
            new_name='team',
        ),
    ]
