# Generated by Django 4.2.5 on 2023-12-05 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0026_rename_teams_department_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='department',
            name='team',
        ),
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.AddField(
            model_name='leader',
            name='department',
            field=models.ForeignKey(default='Service app', help_text='Выберите отдел', on_delete=django.db.models.deletion.CASCADE, to='test_django.department', verbose_name='Название отдела'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(help_text='Введите название проекта', max_length=50, primary_key=True, serialize=False, verbose_name='Название проекта')),
                ('leader', models.ForeignKey(help_text='Выберите тимлида', on_delete=django.db.models.deletion.CASCADE, to='test_django.leader', verbose_name='Тимлид')),
                ('team', models.ManyToManyField(to='test_django.team')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Project',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project', default='Service app', help_text='Выберите проект', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_django.project', verbose_name='Проект'),
        ),
    ]
