# Generated by Django 4.2.5 on 2023-12-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0036_alter_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
