# Generated by Django 4.2.5 on 2023-12-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0044_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_control',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='worker',
        ),
    ]
