# Generated by Django 4.2.5 on 2023-12-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0051_task_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_control',
            field=models.DateTimeField(default=None, help_text='Выберете дату и время сдачи', verbose_name='Дата и время сдачи'),
            preserve_default=False,
        ),
    ]
