# Generated by Django 4.2.5 on 2023-12-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0057_remove_task_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
