# Generated by Django 4.2.5 on 2023-12-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0058_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(help_text='Введите название проекта', max_length=50, primary_key=True, serialize=False, verbose_name='Название проекта')),
                ('leader', models.ForeignKey(help_text='Выберите тимлида', on_delete=django.db.models.deletion.CASCADE, to='test_django.leader', verbose_name='Тимлид')),
                ('team', models.ManyToManyField(to='test_django.team')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Project',
            },
        ),
    ]
