# Generated by Django 4.2.5 on 2023-12-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0064_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department', default='Отдел backend-разработки', help_text='Выберите отдел', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_django.department', verbose_name='Отдел'),
        ),
    ]
