# Generated by Django 4.2.5 on 2023-12-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0066_remove_task_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project', help_text='Выберите проект', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_django.project', verbose_name='Проект'),
        ),
    ]
